# Generated by Django 3.1.1 on 2020-09-11 19:41

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200911_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=myapp.models.product_directory_path),
        ),
    ]
